# Generated by Django 3.2.12 on 2023-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=250)),
                ('passsword', models.CharField(max_length=100)),
                ('r_passsword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=250)),
                ('passsword', models.CharField(max_length=100)),
                ('r_passsword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=250)),
                ('passsword', models.CharField(max_length=100)),
                ('r_passsword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=250)),
                ('passsword', models.CharField(max_length=100)),
                ('r_passsword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
